In [1]:
# KMeans (first assume data normalized)
function KMeans(features::Array{T,2},N = 2) where{T <: AbstractFloat}
    println("feature type is a $T")
    numPoints, numFeatures = size(features);
    assignments = zeros(Int,numPoints);
    centroids  = rand(numFeatures,N);
    oldCentroids  = rand(numFeatures,N);
    newAssignments = ones(T,numPoints);
    currentDistances = zeros(numPoints,N);
    cummulate = zeros(numFeatures,N);
    cummulateNumel = zeros(numFeatures,N);
    centroidMovement = 1;
    # compute distances and assign point to centroid
    for k = 1:20
        for j = 1:N
            currentDistances[:,j] = sum((features .- centroids[:,j]').^2, dims = 2);
        end
        # reassign
        for i = 1:numPoints
            vals, coords = findmin(currentDistances[i,:]);
            assignments[i] = coords;
            cummulate[:, coords] = cummulate[:, coords] + features[i,:];
            cummulateNumel[:,coords] = cummulateNumel[:,coords] .+ 1;
        end
        # recompute centers
        oldCentroids = centroids;
        centroids = cummulate./cummulateNumel;
        centroidMovement = sum((oldCentroids .- centroids).^2);
        println("$oldCentroids")
    end
    assignments
end

KMeans (generic function with 2 methods)

In [2]:
features = [0.0 0.0 0.0 ; 0.1 0.1 0.1 ; 0.9 0.9 0.9 ; 0.8 0.8 0.8 ; 0.3 0.3 0.3 ; 0.4 0.4 0.4 ]

6×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.1  0.1  0.1
 0.9  0.9  0.9
 0.8  0.8  0.8
 0.3  0.3  0.3
 0.4  0.4  0.4

In [3]:
b = KMeans(features,3)

feature type is a Float64
[0.70167 0.0846374 0.489901; 0.332829 0.345669 0.0951115; 0.523949 0.35779 0.714255]
[0.85 0.2 NaN; 0.85 0.2 NaN; 0.85 0.2 NaN]
[0.85 0.2 0.416667; 0.85 0.2 0.416667; 0.85 0.2 0.416667]
[0.85 0.171429 0.414286; 0.85 0.171429 0.414286; 0.85 0.171429 0.414286]
[0.85 0.144444 0.4; 0.85 0.144444 0.4; 0.85 0.144444 0.4]
[0.85 0.127273 0.390909; 0.85 0.127273 0.390909; 0.85 0.127273 0.390909]
[0.85 0.115385 0.384615; 0.85 0.115385 0.384615; 0.85 0.115385 0.384615]
[0.85 0.106667 0.38; 0.85 0.106667 0.38; 0.85 0.106667 0.38]
[0.85 0.1 0.376471; 0.85 0.1 0.376471; 0.85 0.1 0.376471]
[0.85 0.0947368 0.373684; 0.85 0.0947368 0.373684; 0.85 0.0947368 0.373684]
[0.85 0.0904762 0.371429; 0.85 0.0904762 0.371429; 0.85 0.0904762 0.371429]
[0.85 0.0869565 0.369565; 0.85 0.0869565 0.369565; 0.85 0.0869565 0.369565]
[0.85 0.084 0.368; 0.85 0.084 0.368; 0.85 0.084 0.368]
[0.85 0.0814815 0.366667; 0.85 0.0814815 0.366667; 0.85 0.0814815 0.366667]
[0.85 0.0793103 0.365517; 0.85 0.

6-element Array{Int64,1}:
 2
 2
 1
 1
 3
 3

In [67]:
A = rand(7,3)


7×3 Array{Float64,2}:
 0.412217  0.511553   0.191314
 0.343018  0.860371   0.177082
 0.409577  0.861475   0.461032
 0.675696  0.0190763  0.687961
 0.954746  0.984268   0.316622
 0.628194  0.0859921  0.92851 
 0.117172  0.994771   0.29407 

In [66]:
B = rand(2,3)

2×3 Array{Float64,2}:
 0.409065  0.128674  0.622274
 0.831764  0.485986  0.531988

In [53]:
vals, inds = findmax(C,dims = 1)
map(inds->ind2sub(C, inds), inds)

UndefVarError: UndefVarError: ind2sub not defined

In [57]:
val, idx = findmax(view(C,1,:))

(0.42783540868606384, 1)

In [63]:
zeros(Int,2,2)

2×2 Array{Int64,2}:
 0  0
 0  0

In [70]:
import Pkg; Pkg.add("DataFrames")
using DataFrames: columns


  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
Fetching: [========================================>]  100.0 %.0 % Resolving package versions...
 Installed TableTraits ───────────────── v0.4.1
 Installed WeakRefStrings ────────────── v0.5.8
 Installed Tables ────────────────────── v0.1.18
 Installed CodecZlib ─────────────────── v0.5.2
 Installed DataStreams ───────────────── v0.4.1
 Installed TranscodingStreams ────────── v0.9.2
 Installed CategoricalArrays ─────────── v0.5.2
 Installed DataFrames ────────────────── v0.17.1
 Installed IteratorInterfaceExtensions ─ v0.1.1
  Updating `~/.julia/environments/v1.1/Project.toml`
  [a93c6f00] + DataFrames v0.17.1
  Updating `~/.julia/environments/v1.1/Manifest.toml`
  [324d7699] + CategoricalArrays v0.5.2
  [944b1d66] + CodecZlib v0.5.2
  [a93c6f00] + DataFrames v0.17.1
  [9a8bc11e] + DataStreams v0.4.1
  [82899510] + IteratorInterfaceExtensions v0.1.1
  [3783bdb8] + T

┌ Info: Precompiling DataFrames [a93c6f00-e57d-5684-b7b6-d8193f3e46c0]
└ @ Base loading.jl:1186


LoadError: syntax: invalid identifier name "?"

In [92]:
xx = rand(4,3)

4×3 Array{Float64,2}:
 0.0704771  0.716764   0.772697
 0.942944   0.214578   0.941615
 0.587527   0.956369   0.110072
 0.287083   0.0499432  0.344921

In [94]:
cluster = [1 2 3]

1×3 Array{Int64,2}:
 1  2  3

In [95]:
res = (xx.-aa).^2

4×3 Array{Float64,2}:
 0.864013    1.6467   4.96088
 0.00325534  3.18773  4.23695
 0.170134    1.08917  8.35168
 0.50825     3.80272  7.04945

In [98]:
onek = sum(res,dims = 2)

4×1 Array{Float64,2}:
  7.471586224608187
  7.427938727806703
  9.61098354990382 
 11.360417329188692

In [115]:
currentDistances = zeros(4,2)

4×2 Array{Float64,2}:
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0

In [116]:
currentDistances[:,1] = onek
currentDistances

4×2 Array{Float64,2}:
  7.47159  0.0
  7.42794  0.0
  9.61098  0.0
 11.3604   0.0

In [119]:
findmin(currentDistances,dims = 2)

([0.0; 0.0; 0.0; 0.0], CartesianIndex{2}[CartesianIndex(1, 2); CartesianIndex(2, 2); CartesianIndex(3, 2); CartesianIndex(4, 2)])

In [136]:
A = rand(4,3)
N = 2
numPoints, numFeatures = size(A)
assignments = zeros(Int,numPoints)
centroids  = rand(numFeatures,N)
newAssignments = ones(Int,numPoints)
currentDistances = zeros(numPoints,N)

4×2 Array{Float64,2}:
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0

In [137]:
features

4×3 Array{Float64,2}:
 0.799708  0.758403  0.523379
 0.89389   0.163839  0.550673
 0.376039  0.997181  0.566918
 0.228353  0.077301  0.595381

In [140]:
centroids[:,1]

3-element Array{Float64,1}:
 0.4415547568743463 
 0.03092332242429152
 0.37730836818538327

In [141]:
# compute distances and assign point to centroid
for j = 1:N
    currentClusterDistances = sum((features .- centroids[:,j]').^2, dims = 2)
    currentDistances[:,j] = currentClusterDistances
end